export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';
export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const DELETE_CHAT = 'DELETE_CHAT';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const RECIEVE_MESSAGE = 'RECIEVE_MESSAGE';
export const SET_DATA_REGISTER = 'SET_DATA_REGISTER';
